Placement/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Placement.Models;
using Rotativa.AspNetCore;

namespace Placement.Controllers
{
    public class ApplicationsController : Controller
    {
        private readonly MSContext _context;

        public ApplicationsController(MSContext context)
        {
            _context = context;
        }

        // GET: Applications
        public async Task<IActionResult> Index()
        {
            var mSContext = _context.application.Include(a => a.CompanysId).Include(a => a.StudentsId);
            return View(await mSContext.ToListAsync());
            //var ApplicationList = _context.application.ToList();   

            //return View(ApplicationList);
        }

        // GET: Applications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var application = await _context.application
                .Include(a => a.CompanysId)
                .Include(a => a.StudentsId)
                .FirstOrDefaultAsync(m => m.ApplicationID == id);
            if (application == null)
            {
                return NotFound();
            }

            return View(application);
        }

        // GET: Applications/Create
        public IActionResult Create()
        {
            //ViewData["CompanyId"] = new SelectList(_context.company, "CompanyId", "CompanyName");
            //ViewData["StudentId"] = new SelectList(_context.student, "StudentId", "AOI");
            //return View();
            //Student result = _context.student.Find(HttpContext.Session.GetInt32("ApplyStudentId"));
            //var result = new SelectList(from i in _context.student select i.StudentId).ToList();
            //var result1 = new SelectList(from i in _context.company select i.CompanyId).ToList();
            ////ViewBag.StudentId = result;
            //ViewBag.CompanyId = result1;

            //Application C = new Application();
            //ViewBag.CompanyId = C.CompanyId;


            //HttpContext.Session.SetInt32("ApplyCompanyId", (int)C.CompanyId);
            return View();
        }

        // POST: Applications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ApplicationID")] Application application)
        {
            //if (ModelState.IsValid)
            //{
            //application=new Application();
            ////application.StudentId = (int)TempData["StudentId"];
            @ViewBag.StudentId = HttpContext.Session.GetInt32("ApplyStudentId");//Get from Login controller/SLogin
            @ViewBag.CompanyId = HttpContext.Session.GetInt32("ApplyCompanyId");//Get from Companies controller/Details
            //Application a = new Application();
            application.StudentId = ViewBag.StudentId;
            application.CompanyId = ViewBag.CompanyId;
            var result = (from i in _context.application
                          where i.CompanyId == application.CompanyId && i.StudentId == application.StudentId
                          select i).FirstOrDefault();
            if (result == null)
            {
                application.ApplicationDate = DateTime.Now;
                _context.Add(application);
                //ViewBag.application = HttpContext.Session.SetString("PDF", application);
                await _context.SaveChangesAsync();
                ViewBag.SuccessMessage = "Best Wishes,You are successfully applied";
                return View();
            }
            else
            {
                ViewBag.ErrorMessage = "Already Applied";
                return View();
            }
            //}
            //ViewData["CompanyId"] = new SelectList(_context.company, "CompanyId", "CompanyName", application.CompanyId);
            //ViewData["StudentId"] = new SelectList(_context.student, "StudentId", "AOI", application.StudentId);
            //return View(application);
        }

        // GET: Applications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var application = await _context.application.FindAsync(id);
            if (application == null)
            {
                return NotFound();
            }
            ViewData["CompanyId"] = new SelectList(_context.company, "CompanyId", "CompanyName", application.CompanyId);
            ViewData["StudentId"] = new SelectList(_context.student, "StudentId", "AOI", application.StudentId);
            return View(application);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ApplicationID,ApplicationDate,StudentId,CompanyId")] Application application)
        {
            if (id != application.ApplicationID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(application);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationExists(application.ApplicationID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.company, "CompanyId", "CompanyName", application.CompanyId);
            ViewData["StudentId"] = new SelectList(_context.student, "StudentId", "AOI", application.StudentId);
            return View(application);
        }

        // GET: Applications/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var application = await _context.application
                .Include(a => a.CompanysId)
                .Include(a => a.StudentsId)
                .FirstOrDefaultAsync(m => m.ApplicationID == id);
            if (application == null)
            {
                return NotFound();
            }

            return View(application);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var application = await _context.application.FindAsync(id);
            _context.application.Remove(application);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // While converting from .NET5 to .NET6 Print as PDF function not enabled.
        public async Task <IActionResult> DemoViewAsPDF()
        {
            var mSContext = _context.application.Include(a => a.CompanysId).Include(a => a.StudentsId);
            /* List<Application> result = application.ToList();*/    /*new List<Application> ();*/
            return new ViewAsPdf(await mSContext.ToListAsync());
            //return new ViewAsPdf(result);
        }

        private bool ApplicationExists(int id)
        {
            return _context.application.Any(e => e.ApplicationID == id);
        }
    }
}

Placement/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Routing;
using Placement.Models;
using System.Linq;

namespace Placement.Controllers
{
    public class NoDirectAccessAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            var canAcess = false;

            // check the refer
            var referer = filterContext.HttpContext.Request.Headers["Referer"].ToString();
            if (!string.IsNullOrEmpty(referer))
            {
                var rUri = new System.UriBuilder(referer).Uri;
                var req = filterContext.HttpContext.Request;
                if (req.Host.Host == rUri.Host && req.Host.Port == rUri.Port && req.Scheme == rUri.Scheme)
                {
                    canAcess = true;
                }
            }

            // ... check other requirements

            if (!canAcess)
            {
                filterContext.Result = new RedirectToRouteResult(new RouteValueDictionary(new { controller = "Home", action = "Index", area = "" }));
            }
        }
    }
    public class LoginController : Controller
    {
        private readonly MSContext db;
        private readonly ISession session;
        public LoginController(MSContext db, IHttpContextAccessor httpContextAccessor)
        {
            this.db = db;
            session = httpContextAccessor.HttpContext.Session;
        }
        public IActionResult Index()
        {
           
            return View();
        }

        public IActionResult SLogin()
        {
            return View();
        }
        [HttpPost]
        [NoDirectAccess]
        public IActionResult SLogin(Student obj)
        {
            var result = (from i in db.student
                          where i.StudentId == obj.StudentId && i.PassWord == obj.PassWord
                          select i).SingleOrDefault();
           
            ViewBag.StudentId = obj.StudentId;
            HttpContext.Session.SetInt32("LoginStudentId", obj.StudentId);
            ViewBag.StudentId = obj.StudentId;
            HttpContext.Session.SetInt32("ApplyStudentId", obj.StudentId);
            if (result != null)
            {   HttpContext.Session.SetString("PassWord",obj.PassWord); //Password wrong in the sense give error
                HttpContext.Session.SetString("StudentName", result.StudentName);
                return RedirectToAction("Details","Students");
               
            }
            else
            {
                HttpContext.Session.SetString("LoginPassWord", obj.PassWord);
                return View();
            }
        }
        public IActionResult SRegister()
        {
            return View();
        }
        [HttpPost]
        [NoDirectAccess]
        public IActionResult SRegister(Student obj1)
        {
            ViewBag.StudentId = obj1.StudentId;
            if (obj1.StudentId != null)
            {
                db.student.Add(obj1);
                db.SaveChanges();
                HttpContext.Session.SetInt32("StudentId", obj1.StudentId);
                return View();
            }
            else { return View(); }
           
        }
        public IActionResult ALogin()
        {
            return View();
        }
        [HttpPost]
        [NoDirectAccess]
        public IActionResult ALogin(Admin obj)
        {
            var result = (from i in db.admin
                          where i.FacultyId == obj.FacultyId && i.PassWord == obj.PassWord
                          select i).SingleOrDefault();
            ViewBag.PassWord = obj.PassWord;
            HttpContext.Session.SetString("ALoginPassWord", obj.PassWord);
            //ViewBag.FacultyId = obj.FacultyId;
            //HttpContext.Session.SetInt32("AFacultyId", obj.FacultyId);
            if (result != null)
            {
                HttpContext.Session.SetString("FacultyName", result.FacultyName);
                return RedirectToAction("Index","Companies");
              
            }
            else
            {
                HttpContext.Session.SetString("ALoginPassWord", obj.PassWord);
                return View();
            }
        }
        public IActionResult ARegister()
        {
            return View();
        }
        [HttpPost]
        [NoDirectAccess]
        public IActionResult ARegister(Admin obj)
        {
            ViewBag.FacultyId = obj.FacultyId;
            if(obj.FacultyId!= null)
            {
                db.admin.Add(obj);
                db.SaveChanges();
                HttpContext.Session.SetInt32("FacultyId", obj.FacultyId);
                return View();
            }
            else
            {
                return View();
            }
           
            
        }
        [NoDirectAccess]
        public IActionResult Popup()
        {
            return View();
            
        }
        public IActionResult logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

    }

}

Placement/Views/Shared/Common.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Placement</title>
   @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/Template.css" /> 
    <link rel="stylesheet" href="~/css/site.css" />
   
   
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Placement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                  
                   
                   
                </div>
            </div>
        </nav>
    </header>

    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Placement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

    
 

Placement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Placement</title>
   @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/Template.css" /> 
    <link rel="stylesheet" href="~/css/site.css" />
   
   
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Placement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                    </ul>
                  
                    <partial name="_LoginPartial" />
                    
                   
                </div>
            </div>
        </nav>
    </header>

    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Placement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

    
 

Placement/Views/Shared/_LayoutA.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Placement</title>
   @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/Template.css" /> 
    <link rel="stylesheet" href="~/css/site.css" />
   
   
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Placement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index1">Students Data</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Create">Add Company</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Job Notification</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="Index">Applications</a>
                        </li>
                    </ul>
                  
                    <partial name="_LoginPartialA" />
                    
                   
                </div>
            </div>
        </nav>
    </header>

    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Placement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

    
 

Placement/Views/Shared/_LayoutP.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Placement</title>
   @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/Template.css" /> 
    <link rel="stylesheet" href="~/css/site.css" />
   
   
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Placement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                    </ul>
                  
                    <partial name="_LoginPartial" />
                    
                   
                </div>
            </div>
        </nav>
    </header>

    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Placement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

    
 

Placement/Views/Shared/_LayoutS.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Placement</title>
   @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/Template.css" /> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" /> 
    <link rel="stylesheet" href="~/css/site.css" />

   
   
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Placement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                      @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Details">User details</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index1">Job notification</a>
                        </li>
                    </ul>
                  
                    <partial name="_LoginPartialS" />
                    
                   
                </div>
            </div>
        </nav>
    </header>

    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Placement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"/> 
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

    
 

Placement/Views/Shared/_LoginPartialA.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject IHttpContextAccessor HttpContextAccessor



<ul class="navbar-nav">
    @{
        ViewBag.FacultyName = @HttpContextAccessor.HttpContext.Session.GetString("FacultyName");
    }
@if (ViewBag.FacultyName != null)
{
    <li class="nav-item">
       @* <a  class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>*@
        <a id="manage" class="nav-link text-dark" asp-controller="Home" asp-action="Privacy" title="Manage">Hello Prof. @ViewBag.FacultyName</a>
    </li>
    <li class="nav-item">
        <form> @* class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })"*@
            @*<button  type="submit" class="nav-link btn btn-link text-dark">Logout</button>*@
             <button id="logout" type="submit" class="nav-link btn btn-danger text-dark" asp-controller="Login" asp-action="Logout">Logout</button>
        </form>
    </li>
}
else
{
   @*CREATE DROPDOWN IN NAVIGATION METHOD-1*@
  <div class="dropdown">
       <button class="btn btn-block dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Login
       </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
       <a class="dropdown-item" href="Login/SLogin">Student Login</a>
       <a class="dropdown-item" href="Login/ALogin">Admin Login</a>
   
     </div>
  </div>
 
  
  <div class="dropdown">
       <button class="btn btn-block dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Register
       </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
       <a class="dropdown-item" href="Login/SRegister">Student Register</a>
       <a class="dropdown-item" href="Login/ARegister">Admin Register</a>
     </div>
  </div>

  


}
</ul>


 
   

Placement/Views/Shared/_LoginPartialS.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject IHttpContextAccessor HttpContextAccessor



<ul class="navbar-nav">
    @{
        ViewBag.StudentName = @HttpContextAccessor.HttpContext.Session.GetString("StudentName");
        
    }
@if (ViewBag.StudentName != null)
{
    <li class="nav-item">
       @* <a  class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>*@
        <a id="manage" class="nav-link text-dark" asp-controller="Home" asp-action="Privacy" title="Manage">Hello @ViewBag.StudentName</a>
    </li>
   
    <li class="nav-item">
        <form> @* class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })"*@
            @*<button  type="submit" class="nav-link btn btn-link text-dark">Logout</button>*@
             <button id="logout" type="submit" class="nav-link btn btn-danger text-dark" asp-controller="Login" asp-action="Logout">Logout</button>
        </form>
    </li>
}
else
{
   @*CREATE DROPDOWN IN NAVIGATION METHOD-1*@
  <div class="dropdown">
       <button class="btn btn-block dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Login
       </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
       <a class="dropdown-item" href="Login/SLogin">Student Login</a>
       <a class="dropdown-item" href="Login/ALogin">Admin Login</a>
   
     </div>
  </div>
 
  
  <div class="dropdown">
       <button class="btn btn-block dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Register
       </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
       <a class="dropdown-item" href="Login/SRegister">Student Register</a>
       <a class="dropdown-item" href="Login/ARegister">Admin Register</a>
     </div>
  </div>


}
</ul>


 
   